### ISSUE TITLE
Investigate syncing 2 local nodes is not working 

### ISSUE THREAD

**Issue by BeroBurny** [NodeFactoryIo/ChainGuardian#611]
Observed few times that running and syncing 2 nodes (latest case `lighthouse` and `teku`) will fall in some type of limbo and stuck and same syncing state.

<hr />

Tests need to be done
- [ ] test syncing with 2 different networks
- [ ] fully sync one node and run another from 0
- [ ] test main case with 2 same nodes

**Comment by BeroBurny** [comment]
@morrigan did you have this problem with #525 ?
